<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'RW5saXNo');
$cfg_Cs[2]=array(0,1,1,'Q2hpbmVzZQ==');
$cfg_Cs[3]=array(1,6,1,'U2VsZWN0aW9uIG9mIFByb3BlcnRpZXM=');
$cfg_Cs[4]=array(1,1,1,'SW5mbyBmb3IgYnV5ZXJz');
$cfg_Cs[5]=array(1,1,1,'UHJvcGVydHkgTmV3cw==');
$cfg_Cs[6]=array(1,1,1,'Q29udGFjdCBVcw==');
$cfg_Cs[7]=array(2,6,1,'5oi/5Lqn5bGV56S6');
$cfg_Cs[8]=array(2,1,1,'6LSt5Lmw5L+h5oGv');
$cfg_Cs[9]=array(2,1,1,'5oi/5Lqn5paw6Ze7');
$cfg_Cs[10]=array(2,1,1,'6IGU57O75oiR5Lus');
?>