
<field:name itemname="Name" autofield="1" type="text" isnull="true" default=""  maxlength="50" page="">
</field:name>


<field:contactnumber itemname="Telephone No" autofield="1" type="text" isnull="true" default=""  maxlength="15" page="">
</field:contactnumber>


<field:country itemname="Country" autofield="1" type="text" isnull="true" default=""  maxlength="50" page="">
</field:country>

<field:email itemname="Email" autofield="1" type="text" isnull="true" default=""  maxlength="50" page="">
</field:email>

<field:desc itemname="description" autofield="1" type="multitext" isnull="true" default=""  maxlength="500" page="">
</field:desc>

