<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",16,170);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",186,201);
$z[2]=Array("title","",217,231);
$z[3]=Array("city","",291,304);
$z[4]=Array("price","",335,349);
$z[5]=Array("brand","",379,393);
$z[6]=Array("address","",426,442);
$z[7]=Array("description","",488,508);

?>