<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",40,194);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",233,250);
$z[2]=Array("arcurl","",265,280);
$z[3]=Array("title","",296,310);
$z[4]=Array("pubdate","",357,403);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("description","",439,459);

?>