<li>

         <div class="news_left">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>"); [/field:array]</div>

         <div>
         [<b>[field:typelink/]</b>] <a href="[field:arcurl/]" class="title">[field:title/]</a> <span class="info"> <small>Date：</small>[field:pubdate function="GetDateTimeMK(@me)"/]</span>
         <p class="intro"> [field:description/]... </p>
         </div>

        <div style="width:100%;clear:both;height:0px;color: #ffffff"></div>

        </li>