<?php
$z[0]=Array("body","	\n",0,156);
$z[0][4]['itemname']="详细介绍";
$z[0][4]['autofield']="1";
$z[0][4]['notsend']="0";
$z[0][4]['type']="htmltext";
$z[0][4]['isnull']="true";
$z[0][4]['islist']="0";
$z[0][4]['default']="";
$z[0][4]['maxlength']="";
$z[0][4]['page']="split";
$z[1]=Array("price","\r\n	\r\n",158,307);
$z[1][4]['itemname']="市场价";
$z[1][4]['autofield']="1";
$z[1][4]['notsend']="0";
$z[1][4]['type']="text";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="1";
$z[1][4]['default']="";
$z[1][4]['maxlength']="";
$z[1][4]['page']="";

?>