<li>
      				<div class="productleft">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}'/>"); [/field:array]</div>
					<div class="productright">
                        <p><strong> [field:title/]</strong></p>
                        <p><span>
                            <small>City：[field:city/]</small> &nbsp;&nbsp;&nbsp;
                            <small>Price：[field:price/]</small>&nbsp;&nbsp;&nbsp;
                            <small>Type：[field:type/]</small>
                        </span>
                        </p>
                        <p>
                            <span><small>Address：[field:address/]</small></span>
                        </p>
                        <p class="introd">
                            [field:details/]
                        </p>
                    </div>

                    <div style="width:100%;clear:both;height:0px;color: #ffffff"></div>
				</li>