<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",5,159);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",174,191);
$z[2]=Array("arcurl","",206,221);
$z[3]=Array("title","",237,251);
$z[4]=Array("pubdate","",300,346);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",371,385);
$z[6]=Array("scores","",410,425);
$z[7]=Array("description","",462,482);

?>