<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",39,193);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",250,267);
$z[2]=Array("arcurl","",282,297);
$z[3]=Array("title","",313,327);
$z[4]=Array("pubdate","",374,420);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("description","",456,476);

?>