<?php
$z[0]=Array("name","\r\n",1,119);
$z[0][4]['itemname']="Name";
$z[0][4]['autofield']="1";
$z[0][4]['type']="text";
$z[0][4]['isnull']="true";
$z[0][4]['default']="";
$z[0][4]['maxlength']="50";
$z[0][4]['page']="";
$z[1]=Array("contactnumber","\r\n",124,266);
$z[1][4]['itemname']="Tel Number";
$z[1][4]['autofield']="1";
$z[1][4]['type']="text";
$z[1][4]['isnull']="true";
$z[1][4]['default']="";
$z[1][4]['maxlength']="15";
$z[1][4]['page']="";

?>