<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,386);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",426,477);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",495,527);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",616,651);
$z[6][4]['filename']="head.htm";
$z[7]=Array("field","",764,783);
$z[7][4]['name']="title";
$z[8]=Array("field","",870,926);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[9]=Array("field","",974,994);
$z[9][4]['name']="source";
$z[10]=Array("field","",1043,1063);
$z[10][4]['name']="writer";
$z[11]=Array("field","\r\n  if(@me<>'' )@me = '\r\n  <div class=\"introduce\">'.@me.'</div>\r\n  ';\r\n  ",1105,1240);
$z[11][4]['name']="description";
$z[11][4]['runphp']="yes";
$z[12]=Array("field","",1279,1297);
$z[12][4]['name']="body";
$z[13]=Array("prenext","",1465,1490);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",1506,1532);
$z[14][4]['get']="next";
$z[15]=Array("include","",1610,1647);
$z[15][4]['filename']="footer.htm";

?>