<li>
      				<div class="productleft">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>"); [/field:array]</div>
					<div class="productright">
                        <p> [field:title/]</p>
                        <p><span>
                            <small>City：</small>[field:city/]
                            <small>Price：</small>[field:price/]
                            <small>Type：</small>[field:type/]
                        </span>
                        </p>
                        <p>
                            <span><small>Address：</small>[field:address/]</span>
                        </p>
                        <p class="intro">
                            [field:description/]...
                        </p>
                    </div>

                    <div style="width:100%;clear:both;height:1px;color: #ffffff"></div>
				</li>