<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",16,170);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",186,201);
$z[2]=Array("title","",217,231);
$z[3]=Array("city","",278,291);
$z[4]=Array("price","",322,336);
$z[5]=Array("brand","",366,380);
$z[6]=Array("address","",413,429);
$z[7]=Array("description","",475,495);

?>