<field:body itemname="productdetails" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="1000" page="split">
	
</field:body>

	
<field:price itemname="Price" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="" page="">
	
</field:price>

<field:city itemname="City" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:city>

<field:type itemname="Type" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:type>

<field:address itemname="Address" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:address>

<field:details itemname="details" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="1000" page="">
</field:details>
