<li>
         <div class="newsleft">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}'/></a>"); [/field:array]</div>
         <div class="newsright">
         <p>[<b>[field:typelink/]</b>] <a href="[field:arcurl/]">[field:title/]</a></p>
         <p><span class="info"> <small>Date：[field:pubdate function="GetDateTimeMK(@me)"/]</small></span></p>
         <p class="intro"> [field:description/]... </p>
         </div>

        <div style="width:100%;clear:both;height:0px;color: #ffffff"></div>

        </li>