<?php
$z[0]=Array("global","",107,134);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",146,178);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",225,251);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",601,626);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n                <li><a href='[field:typelink/]' target=\"_blank\">[field:typename/]</a> </li>\r\n                ",662,900);
$z[4][4]['type']="top";
$z[4][4]['row']="8";
$z[4][4]['currentstyle']="<li class='thisclass'><a href='~typelink~'>~typename~</a> </li>";

?>