<?php
$z[0]=Array("global","",103,130);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",142,174);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",210,236);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",346,371);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",436,461);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",637,662);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("sql","\r\n                <li><a href=\"[field:typedir function='str_replace(\"{cmspath}\",\"\",@me)'/]\"  class=\"depth_3\">[field:typename/]</a></li>\r\n                ",701,946);
$z[6][4]['sql']="Select * from dede_arctype where reid=2 ORDER BY id limit 00,20";

?>