<?php
$z[0]=Array("global","",103,130);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",145,177);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",213,239);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",349,374);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",439,464);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("mytag","",563,594);
$z[5][4]['name']="contact-ch";
$z[6]=Array("global","",732,757);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("sql","\r\n                <li><a href=\"[field:typedir function='str_replace(\"{cmspath}\",\"\",@me)'/]\"  class=\"depth_3\">[field:typename/]</a></li>\r\n                ",796,1041);
$z[7][4]['sql']="Select * from dede_arctype where reid=2 ORDER BY id limit 00,20";

?>